name: run build
on:
  push:
    paths-ignore:
    - 'README.md'
    - 'documentation/**'
  workflow_dispatch:
  pull_request:

jobs:
  build-app:
    name: Setup project and build it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies 
        working-directory: ./src
        run: npm ci
      - name: build App 
        working-directory: ./src
        run: npm run build
